// src/lib/platform-config/config-defaults.ts
// ─── Static Fallback Defaults ───────────────────────────────────────────────
// Mirrors the values seeded by seedPlatformConfig(). If the PlatformConfig
// DB row for a key is missing at read time, getRaw() falls back to the
// value here so that pages never crash due to unseeded config. Admins
// should still run the seed so values are editable from the admin UI.
//
// Keep this file in sync with config-seed.ts.

import { CONFIG_KEYS, type ConfigKey } from "./config-keys";

export const CONFIG_DEFAULTS: Record<ConfigKey, string> = {
  // ── SELLER_TIERS ──────────────────────────────────────────────────────────
  [CONFIG_KEYS.GOLD_MIN_SALES]: "50",
  [CONFIG_KEYS.GOLD_MIN_RATING]: "4.5",
  [CONFIG_KEYS.GOLD_MIN_COMPLETION_RATE]: "95",
  [CONFIG_KEYS.SILVER_MIN_SALES]: "20",
  [CONFIG_KEYS.SILVER_MIN_RATING]: "4.0",
  [CONFIG_KEYS.SILVER_MIN_COMPLETION_RATE]: "90",
  [CONFIG_KEYS.BRONZE_MIN_SALES]: "5",
  [CONFIG_KEYS.BRONZE_MIN_RATING]: "3.5",
  [CONFIG_KEYS.BRONZE_MIN_COMPLETION_RATE]: "80",
  [CONFIG_KEYS.BASIC_MAX_LISTINGS]: "10",
  [CONFIG_KEYS.PHONE_MAX_LISTINGS]: "50",
  [CONFIG_KEYS.BASIC_PAYOUT_DELAY_DAYS]: "7",
  [CONFIG_KEYS.PHONE_PAYOUT_DELAY_DAYS]: "3",
  [CONFIG_KEYS.ID_PAYOUT_DELAY_DAYS]: "1",

  // ── FINANCIAL ─────────────────────────────────────────────────────────────
  [CONFIG_KEYS.SHIPPING_SAME_REGION_CENTS]: "600",
  [CONFIG_KEYS.SHIPPING_SAME_ISLAND_CENTS]: "800",
  [CONFIG_KEYS.SHIPPING_INTER_ISLAND_CENTS]: "1200",
  [CONFIG_KEYS.SHIPPING_RURAL_SURCHARGE_CENTS]: "400",
  [CONFIG_KEYS.L1_MAX_PRICE_CENTS]: "10000",
  [CONFIG_KEYS.PLATFORM_MAX_PRICE_CENTS]: "5000000",
  [CONFIG_KEYS.ESCROW_RELEASE_BUSINESS_DAYS]: "4",
  [CONFIG_KEYS.OFFER_MIN_PERCENTAGE]: "50",
  [CONFIG_KEYS.PLATFORM_FEE_STANDARD_RATE]: "3.5",
  [CONFIG_KEYS.PLATFORM_FEE_SILVER_RATE]: "3.0",
  [CONFIG_KEYS.PLATFORM_FEE_GOLD_RATE]: "2.5",
  [CONFIG_KEYS.PLATFORM_FEE_MINIMUM_CENTS]: "50",
  [CONFIG_KEYS.PLATFORM_FEE_MAXIMUM_CENTS]: "5000",
  [CONFIG_KEYS.STRIPE_FEE_RATE]: "1.9",
  [CONFIG_KEYS.STRIPE_FEE_FIXED_CENTS]: "30",

  // ── TIME_LIMITS ───────────────────────────────────────────────────────────
  [CONFIG_KEYS.FREE_CANCEL_WINDOW_MINUTES]: "60",
  [CONFIG_KEYS.CANCEL_REQUEST_WINDOW_HOURS]: "24",
  [CONFIG_KEYS.DISPUTE_OPEN_WINDOW_DAYS]: "14",
  [CONFIG_KEYS.DISPUTE_SELLER_RESPONSE_HOURS]: "72",
  [CONFIG_KEYS.DISPUTE_COOLING_PERIOD_HOURS]: "24",
  [CONFIG_KEYS.RETURN_RESPONSE_WINDOW_HOURS]: "72",
  [CONFIG_KEYS.PARTIAL_REFUND_RESPONSE_HOURS]: "48",
  [CONFIG_KEYS.CART_EXPIRY_HOURS]: "48",
  [CONFIG_KEYS.OFFER_EXPIRY_HOURS]: "72",
  [CONFIG_KEYS.TRUST_METRICS_CACHE_HOURS]: "24",
  [CONFIG_KEYS.TRUST_SCORE_ROLLING_DAYS]: "30",
  [CONFIG_KEYS.SHIPPING_DELAY_NOTIFICATION_DAYS]: "7",

  // ── LISTING_RULES ─────────────────────────────────────────────────────────
  [CONFIG_KEYS.LISTING_MIN_TITLE_LENGTH]: "5",
  [CONFIG_KEYS.LISTING_MAX_TITLE_LENGTH]: "80",
  [CONFIG_KEYS.LISTING_MIN_DESCRIPTION_LENGTH]: "50",
  [CONFIG_KEYS.LISTING_SHORT_DESC_THRESHOLD]: "100",
  [CONFIG_KEYS.LISTING_HIGH_VALUE_THRESHOLD_CENTS]: "50000",
  [CONFIG_KEYS.LISTING_L1_MAX_ACTIVE]: "3",
  [CONFIG_KEYS.LISTING_AUTO_PUBLISH_MAX_SCORE]: "29",
  [CONFIG_KEYS.LISTING_MAX_IMAGES]: "10",
  [CONFIG_KEYS.LISTING_DUPLICATE_WINDOW_DAYS]: "7",
  [CONFIG_KEYS.LISTING_FIRST_LISTINGS_THRESHOLD]: "3",

  // ── FRAUD_RULES ───────────────────────────────────────────────────────────
  [CONFIG_KEYS.RISK_SCORE_SINGLE_IMAGE]: "15",
  [CONFIG_KEYS.RISK_SCORE_SHORT_DESC]: "15",
  [CONFIG_KEYS.RISK_SCORE_PHONE_IN_LISTING]: "45",
  [CONFIG_KEYS.RISK_SCORE_EMAIL_IN_LISTING]: "45",
  [CONFIG_KEYS.RISK_SCORE_EXTERNAL_URL]: "35",
  [CONFIG_KEYS.RISK_SCORE_RISK_KEYWORD]: "30",
  [CONFIG_KEYS.RISK_SCORE_HIGH_DISPUTE_RATE]: "40",
  [CONFIG_KEYS.RISK_SCORE_NEW_SELLER]: "20",
  [CONFIG_KEYS.RISK_SCORE_HIGH_VALUE]: "50",
  [CONFIG_KEYS.RISK_SCORE_DUPLICATE]: "50",
  [CONFIG_KEYS.RISK_SCORE_FIRST_LISTINGS]: "30",
  [CONFIG_KEYS.SELLER_HIGH_DISPUTE_RATE_PCT]: "10",
  [CONFIG_KEYS.AUTO_REFUND_SCORE_THRESHOLD]: "60",
  [CONFIG_KEYS.AUTO_DISMISS_SCORE_THRESHOLD]: "-40",
  [CONFIG_KEYS.BUYER_FRAUD_DISPUTE_LIMIT]: "5",
  [CONFIG_KEYS.SELLER_FRAUD_DISPUTE_RATE_PCT]: "20",
  [CONFIG_KEYS.BUYER_HUMAN_REVIEW_AFTER]: "3",
  [CONFIG_KEYS.SELLER_DOWNGRADE_DISPUTE_RATE_PCT]: "15",
  [CONFIG_KEYS.SELLER_DOWNGRADE_OPEN_DISPUTES]: "3",
  [CONFIG_KEYS.DISPUTE_SELLER_UNRESPONSIVE_HOURS]: "72",
  [CONFIG_KEYS.DISPUTE_SELLER_HIGH_RATE_PCT]: "15",
  [CONFIG_KEYS.DISPUTE_SELLER_HIGH_RATE_MIN_ORDERS]: "5",
  [CONFIG_KEYS.DISPUTE_BUYER_HIGH_DISPUTES_DAYS]: "30",
  [CONFIG_KEYS.DISPUTE_BUYER_HIGH_DISPUTES_COUNT]: "5",
  [CONFIG_KEYS.DISPUTE_SELLER_LOW_RATE_PCT]: "5",
  [CONFIG_KEYS.DISPUTE_SELLER_LOW_RATE_MIN_ORDERS]: "5",

  // ── PICKUP_RULES ──────────────────────────────────────────────────────────
  [CONFIG_KEYS.PICKUP_MIN_LEAD_TIME_HOURS]: "2",
  [CONFIG_KEYS.PICKUP_MAX_HORIZON_DAYS]: "30",
  [CONFIG_KEYS.PICKUP_WINDOW_MINUTES]: "30",
  [CONFIG_KEYS.PICKUP_RESCHEDULE_LIMIT]: "3",
  [CONFIG_KEYS.PICKUP_RESCHEDULE_RESPONSE_HOURS]: "12",
  [CONFIG_KEYS.PICKUP_SCHEDULE_DEADLINE_HOURS]: "48",
  [CONFIG_KEYS.PICKUP_OTP_EXPIRY_MINUTES]: "30",
  [CONFIG_KEYS.PICKUP_OTP_EARLY_INITIATION_MINUTES]: "15",
};
